export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';

export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';
export const RECEIVE_RECIPE = 'RECEIVE_RECIPE';
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_RECIPES_ERROR = 'GET_ALL_RECIPES_ERROR';
export const GET_PAGE_DETAILS = 'GET_PAGE_DETAILS';
export const GET_MY_RECIPES = 'GET_MY_RECIPES';
export const GET_MY_RECIPES_FAIL = 'GET_MY_RECIPES_FAIL';
export const DELETE_RECEIPE = 'DELETE_RECEIPE';
export const DELETE_RECEIPE_FAIL = 'DELETE_RECEIPE_FAIL';
export const GET_MY_RECIPES_PAGE_COUNT = 'GET_MY_RECIPES_PAGE_COUNT';
export const GET_MOST_UPVOTES_COUNT = 'GET_MOST_UPVOTES_COUNT';
export const RECEIVE_RECIPE_ERROR = 'RECEIVE_RECIPE_ERROR';

export const ADD_UPVOTE = 'ADD_UPVOTE';
export const GET_DOWNVOTE = 'GET_DOWNVOTE';
export const UPVOTE_RECIPE = 'UPVOTE_RECIPE';

export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const UPDATE_RECIPE_ERROR = 'UPDATE_RECIPE_ERROR';

export const GET_ALL_FAVORITES = 'GET_ALL_FAVORITES';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const FAVORITE_ID = 'FAVORITE_ID';
export const GET_ALL_FAVORITES_PAGE_COUNT = 'GET_ALL_FAVORITES_PAGE_COUNT';
export const GET_ALL_FAVORITES_FAIL = 'GET_ALL_FAVORITES_FAIL';

export const GET_MOST_UPVOTES = 'GET_MOST_UPVOTES';
export const GET_MOST_UPVOTES_ERROR = 'GET_MOST_UPVOTES_ERROR';

export const GET_SEARCHED_RECIPE = 'GET_SEARCHED_RECIPE';
export const GET_SEARCHED_RECIPE_COUNT = 'GET_SEARCHED_RECIPE_COUNT';

export const ADD_REVIEW = 'ADD_REVIEW';
export const GET_REVIEW = 'GET_REVIEW';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';
