export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';

export const RECEIVE_RECIPE = 'RECEIVE_RECIPE';
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_PAGE_DETAILS = 'GET_PAGE_DETAILS';

export const ADD_UPVOTE = 'ADD_UPVOTE';
export const GET_DOWNVOTE = 'GET_DOWNVOTE';
export const GET_UPVOTE = 'GET_UPVOTE';

export const UPDATE_RECIPE = 'UPDATE_RECIPE';

export const GET_ALL_FAVORITES = 'GET_ALL_FAVORITES';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';

export const GET_MOST_UPVOTES = 'GET_MOST_UPVOTES';

export const GET_SEARCHED_RECIPE = 'GET_SEARCHED_RECIPE';

export const ADD_REVIEW = 'ADD_REVIEW';
export const GET_REVIEW = 'GET_REVIEW';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';
